sudo: required
services:
  - docker

before_install:
  - docker build -t aminbavand/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aminbavand/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  #DockerReact-env.eba-h3zrkuay.us-east-2.elasticbeanstalk.com
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-710852728941"
  bucket_path: "docker-react"
  #only deploy branch master changes:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
